apiVersion: apps/v1
kind: Deployment
metadata:
  name: actions-runner
  namespace: semits-system
spec:
  selector:
    matchLabels:
      app: actions-runner
  template:
    metadata:
      labels:
        app: actions-runner
    spec:
      containers:
        - name: runner
          image: semits/runner:2.80.3
          env:
            - name: GITHUB_OWNER
              value: ""
            - name:  GITHUB_TOKEN
              value: ""
          volumeMounts:
            - name: docker-sock
              mountPath: /var/run/docker.sock
      volumes:
      - name: docker-sock
        hostPath:
          path: /var/run/docker.sock